name: peba_app
description: A silent weapon for tired workers to claim unpaid overtime.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Core / UI ---
  flutter_riverpod: ^2.4.9 # 状態管理
  intl: ^0.20.2 # 日付や通貨のフォーマット
  uuid: ^4.2.2 # 固有ID生成

  # --- Firebase (Backend) ---
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3 # 匿名認証
  cloud_firestore: ^6.1.1 # ログ保存

  # --- Sensor & Background ---
  geolocator: ^10.1.0 # GPS取得
  flutter_background_service: ^5.0.0 # バックグラウンド動作
  flutter_local_notifications: ^17.0.0 # 通知（常駐用）
  permission_handler: ^11.1.0 # 面倒な権限許可を管理

  # --- Security & Evidsence ---
  ntp: ^2.0.0 # 正確な時刻取得（改ざん防止）
  crypto: ^3.0.3 # SHA-256ハッシュ化
  shared_preferences: ^2.2.2 # 設定（職場位置）の保存
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true